import fs from 'node:fs';
import path from 'node:path';
const site=JSON.parse(fs.readFileSync('content/site.json','utf8'));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
if(!/^https:\/\//.test(site.siteUrl)||!/^https:\/\//.test(site.contactUrl))throw Error('Use HTTPS URLs');
const slugs=new Set();
for(const p of site.projects){if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(p.slug)||slugs.has(p.slug))throw Error('Invalid or duplicate slug');slugs.add(p.slug);if(p.image&&(!/^assets\/[a-zA-Z0-9/_.-]+$/.test(p.image)||p.image.includes('..')||!fs.existsSync('public/'+p.image)))throw Error('Missing/invalid project image');}
fs.mkdirSync('dist',{recursive:true});
for(const f of ['styles.css','main.js'])fs.copyFileSync('src/'+f,'dist/'+f);
fs.cpSync('public','dist',{recursive:true});
const base=site.siteUrl.replace(/\/?$/,'/');
const head=(title,description,url,prefix='')=>`<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${esc(url)}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:url" content="${esc(url)}"><meta name="theme-color" content="#ffe500"><link rel="icon" href="${prefix}favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="${prefix}styles.css"><script src="${prefix}main.js" defer></script></head><body><a class="skip" href="#main">跳至内容</a>`;
const art=(p,prefix='')=>p.image?`<img src="${prefix}${esc(p.image)}" alt="${esc(p.imageAlt||p.title)}" loading="lazy" width="1200" height="900">`:`<div class="art art-${esc(p.theme)}" aria-hidden="true">${p.theme==='form'?'<div class="orbit"></div><span>FORM<br>STUDY.</span>':p.theme==='type'?'<span>Aa<br>Bb.</span><i>THE SHAPE OF WORDS / 02</i>':'<div class="rings"></div><span>IN<br>MOTION.</span>'}</div>`;
const footer=(prefix='')=>`<footer><a class="wordmark" href="${prefix||'./'}">${esc(site.name)}<span>®</span></a><span>© ${new Date().getFullYear()} / PERSONAL PORTFOLIO</span><a href="#top">回到顶部 ↑</a></footer><div class="cursor" aria-hidden="true"></div></body></html>`;
const cards=site.projects.map((p,i)=>`<article class="project reveal" data-category="${esc(p.category)}"><a class="project-link" href="projects/${p.slug}/"><div class="cover">${art(p)}<span class="view">查看项目 ↗</span></div><div class="project-meta"><span>0${i+1} / ${esc(p.category)}</span><span>${esc(p.year)}${p.demo?' · 设计示例':''}</span></div><h3>${esc(p.title)}</h3><p>${esc(p.summary)}</p></a></article>`).join('');
const categories=[...new Set(site.projects.map(p=>p.category))];
fs.writeFileSync('dist/index.html',head(site.title,site.description,base)+`<header id="top"><a class="wordmark" href="./">${esc(site.name)}<span>®</span></a><nav aria-label="主导航"><a href="#work">作品 / WORK</a><a href="#about">关于 / ABOUT</a><a href="#contact">联系 ↗</a></nav><span class="edition">PORTFOLIO — 2026</span></header><main id="main"><section class="hero" aria-labelledby="hero-title"><div class="micro hero-label">INDEPENDENT SPACE<br>FOR IDEAS & EXPERIMENTS</div><div class="hero-art" aria-hidden="true"><div class="petals">${'<i></i>'.repeat(6)}</div><span class="art-caption">PLAY WITH THE POSSIBILITIES</span></div><span class="micro hero-side">#001<br>ALWAYS EXPLORING</span><div class="hero-bottom"><h1 id="hero-title">MAKE<br><span class="outline">ROOM.</span></h1><div class="hero-note"><p>${esc(site.intro)}</p><a class="round-link" href="#work" aria-label="浏览作品">↓</a></div></div><div class="hero-foot micro"><span>VISUAL / INTERACTION / EXPERIMENT</span><span>SCROLL TO EXPLORE ↓</span></div></section><section id="work" class="work"><div class="section-head"><span class="micro">01 / SELECTED WORK</span><h2>想法，<br>有了形状<span class="yellow-dot">.</span></h2><p>作品与探索的存档。<br>当前项目为版式设计示例。</p></div><div class="filters" role="group" aria-label="作品分类"><button class="active" data-filter="全部" aria-pressed="true">全部 <sup>${site.projects.length.toString().padStart(2,'0')}</sup></button>${categories.map(c=>`<button data-filter="${esc(c)}" aria-pressed="false">${esc(c)}</button>`).join('')}</div><div class="projects">${cards}</div><p id="empty" hidden>这个分类暂时没有作品。</p></section><section id="about" class="about"><span class="micro">02 / A LITTLE ABOUT ME</span><div><h2>好奇心，<br>还在继续<span class="yellow-dot">.</span></h2><p>${esc(site.about)}</p><div class="about-tags"><span>VISUAL</span><span>INTERACTION</span><span>EXPERIMENT</span></div></div></section><section id="contact" class="contact"><span class="micro">03 / KEEP IN TOUCH</span><a href="${esc(site.contactUrl)}" target="_blank" rel="noopener noreferrer"><span>LET’S<br>TALK.</span><span class="contact-arrow">↗</span></a><p>${esc(site.contactLabel)}</p></section></main><nav class="dock" aria-label="快捷导航"><a href="#work">作品</a><span>/</span><a href="#about">关于</a><span>/</span><a href="#contact">联系 ↗</a></nav>`+footer());
for(const [i,p]of site.projects.entries()){const dir='dist/projects/'+p.slug;fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/index.html',head(p.title+' — '+site.name,p.summary,base+'projects/'+p.slug+'/', '../../')+`<header id="top"><a class="wordmark" href="../../">${esc(site.name)}<span>®</span></a><a href="../../#work">← 返回作品</a><span class="edition">PROJECT / 0${i+1}</span></header><main id="main" class="detail"><div class="detail-head"><span class="micro">${esc(p.category)} / ${esc(p.year)}${p.demo?' / 设计示例':''}</span><h1>${esc(p.title)}</h1><p>${esc(p.summary)}</p></div><div class="detail-art">${art(p,'../../')}</div><section class="detail-body"><span class="micro">ABOUT THE PROJECT</span><p>${esc(p.description)}</p></section><a class="next" href="../${site.projects[(i+1)%site.projects.length].slug}/">下一个项目 <span>↗</span></a></main>`+footer('../../'));}
fs.writeFileSync('dist/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${[base,...site.projects.map(p=>base+'projects/'+p.slug+'/')].map(u=>`<url><loc>${esc(u)}</loc></url>`).join('')}</urlset>`);
fs.writeFileSync('dist/robots.txt',`User-agent: *\nAllow: /\nSitemap: ${base}sitemap.xml\n`);
fs.writeFileSync('dist/404.html',head('页面未找到 — '+site.name,'页面不存在',base)+`<main class="detail"><h1>404 / LOST IN SPACE.</h1><p>这个页面不存在，可能已被移动。</p><a href="${esc(base)}">返回首页 ↗</a></main></body></html>`);
fs.writeFileSync('dist/.nojekyll','');
console.log(`Built homepage + ${site.projects.length} project pages in dist/`);
