export function renderCaseStudy(p,esc){
const asset='../../assets/something-lurking/';
const figure=(file,alt,caption)=>`<figure class="case-figure"><a href="${asset}${file}" target="_blank" rel="noopener" aria-label="Open full-size image: ${esc(alt)}"><img src="${asset}${file}" alt="${esc(alt)}" loading="lazy"></a><figcaption>${caption}</figcaption></figure>`;
return `<div class="case-intro"><span class="micro">VR EXPLORATION / 2025</span><h1>Something<br>Lurking<span class="yellow-dot">.</span></h1><p class="case-deck">Designing tension through space, scale, and discovery.</p></div>
<dl class="case-facts"><div><dt>MY ROLE</dt><dd>Art Director &amp;<br>Level Designer</dd></div><div><dt>TIMEFRAME</dt><dd>1 month / 2025</dd></div><div><dt>FORMAT</dt><dd>Collaborative VR project</dd></div><div><dt>TOOLS</dt><dd>Unity XR Interaction Toolkit<br>Blender / Substance Designer</dd></div></dl>
<div class="case-cover"><img src="${asset}overview.png" width="1030" height="835" alt="Green-toned astronaut artwork for Something Lurking"><div><span class="micro">AN ABANDONED SPACE STATION.</span><p>Three scales.<br>One uneasy<br>journey.</p></div></div>
<div class="case-outcome"><span class="micro">OUTCOME</span><p>The final demo was selected by Simon Fraser University for a showcase introducing prospective students to the course’s work.</p></div>
<nav class="case-nav" aria-label="Case study sections"><a href="#challenge">The challenge</a><a href="#contribution">My contribution</a><a href="#decisions">Design decisions</a><a href="#production">Production</a><a href="#reflection">Reflection</a></nav>
<section class="case-section" id="challenge"><span class="micro">01 / THE CHALLENGE</span><div><h2>Make the environment<br>carry the tension.</h2><p>Something Lurking is an immersive VR exploration experience inside an abandoned space station. Our goal was a slow-burn psychological journey driven by discovery rather than combat.</p><p>The design challenge was to make scale changes meaningful to play while keeping objectives and interactions grounded in the world. Space, lighting, and sound needed to communicate what to do—and when something felt wrong.</p></div></section>
<section class="case-section" id="contribution"><span class="micro">02 / MY CONTRIBUTION</span><div><h2>From critique to<br>a coherent world.</h2><p>Peer feedback and external playtesting pointed to three needs: clearer environmental progression, more legible puzzle logic, and a stronger emotional arc.</p><p>I led the restructuring of the spatial and narrative framework. I translated those discussions into whiteboard flow diagrams, level progression maps, and concepts for the control room, garage, chip-space puzzle, and escape vehicle interior.</p><ul class="case-list"><li><strong>Art direction:</strong> established the visual language and kept environments consistent.</li><li><strong>Level design:</strong> shaped spatial progression and the gameplay loop across three scales.</li><li><strong>Environment production:</strong> modeled most in-game environments in Blender and developed materials in Substance Designer.</li></ul><p class="case-note">The interaction systems described below were part of the team’s shared VR production. My primary ownership was art direction, level design, and environment creation.</p></div></section>
${figure('planning.png','Planning board with peer critique, level flow mapping, and room concepts','Planning evidence: critique was translated into spatial diagrams and concepts for the later acts. Open the image to inspect the original board.')}
<section class="case-section" id="decisions"><span class="micro">03 / DESIGN DECISIONS</span><div><h2>A familiar space.<br>An unfamiliar scale.</h2><p>Three linked decisions shaped the experience: a gradual narrative descent, an interface attached to the player, and interactions that make the environment feel physical.</p></div></section>
<div class="act-grid"><article><span class="micro">ACT I / ROUTINE</span><h3>Establish safety.</h3><p>A calm tutorial and fuse-repair task introduce the station and its interaction rules.</p></article><article><span class="micro">ACT II / DESCENT</span><h3>Take it away.</h3><p>Power loss brings darkness and isolation, turning familiar navigation into uncertainty.</p></article><article><span class="micro">ACT III / BREACH</span><h3>Leave a question.</h3><p>A restoration attempt leads to an ambiguous escape and a cliffhanger, preserving unresolved tension.</p></article></div>
<div class="decision-grid"><article><span class="micro">01 / SCALE AS A MECHANIC</span><h3>1:1 → 1:100 → 1:1000</h3><p>Scale switching lets the station be explored at different spatial levels, connecting navigation with the fusebox and chip-space puzzle.</p><details class="motion-demo"><summary>View scale-switching gameplay <span>+</span></summary><img src="${asset}scale.gif" width="426" height="240" alt="VR gameplay showing the player scaling down" loading="lazy"></details></article><article><span class="micro">02 / A WORLD-BOUND INTERFACE</span><h3>Keep guidance on the wrist.</h3><p>The wrist interface brings scale controls, the flashlight toggle, and objective guidance into the world instead of placing a detached overlay in front of the player.</p>${figure('wrist.png','3D model of the wrist-mounted control device','Wrist device model supporting the diegetic interface.')}</article><article><span class="micro">03 / TACTILE PRESENCE</span><h3>Let the player handle it.</h3><p>Constrained sliding doors, object pickup, grid placement, and two-hand wire scaling make tasks physical. Detection zones coordinate lighting, sound, doors, and progression.</p><details class="motion-demo"><summary>View elevator interaction <span>+</span></summary><img src="${asset}interaction.gif" width="426" height="240" alt="VR gameplay demonstrating physical elevator interaction" loading="lazy"></details></article></div>
<section class="case-section" id="production"><span class="micro">04 / ENVIRONMENT PRODUCTION</span><div><h2>Build for atmosphere.<br>Build for navigation.</h2><p>I carried the planning into environmental models, materials, and spatial flow. The station needed a consistent visual identity across corridors, machinery, miniature spaces, and the escape sequence.</p><p>The production combined original modeling with external assets from Sketchfab and PBR libraries. The images below document the project’s environment and prop work.</p></div></section>
${figure('environment.png','Production board showing station environments, scale-specific spaces, props, and tools','Environment and asset overview from the original project presentation.')}
<div class="case-gallery">${figure('pod.png','Escape pod design and 3D model','Escape pod: exterior design and model.')}${figure('elevator.png','Elevator model and orthographic view','Elevator: model and orthographic view.')}${figure('astronaut.png','Non-photorealistic render of the astronaut model','Astronaut: non-photorealistic rendering study.')}</div>
<section class="case-section" id="reflection"><span class="micro">05 / REFLECTION</span><div><h2>Direction before detail.</h2><p>The defining iteration was the spatial and narrative restructure: it gave the team a shared foundation for later environment and interaction work. The strongest part of this case is the connection between feedback, planning artifacts, and the produced world.</p><p class="case-note">The documented outcome is the completed demo and SFU showcase selection. This case does not claim measured improvements in player performance or usability.</p><a class="case-source" href="https://ericgabriel-iat.com/work/something-lurking/" target="_blank" rel="noopener">Original project archive ↗</a></div></section>`;
}
